"""empty message

Revision ID: e23899da65c4
Revises: 50f7d62ced21
Create Date: 2023-12-19 15:00:23.070161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23899da65c4'
down_revision = '50f7d62ced21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item_table', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
